# Generated by Django 3.2.12 on 2022-04-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220419_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_confirmed',
        ),
    ]
