# Generated by Django 3.2.12 on 2022-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220420_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
