# Generated by Django 3.2.12 on 2022-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220420_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default='False'),
        ),
    ]
