# Generated by Django 3.2.12 on 2022-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_has_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
